---
name: CI with CUDA

on:
  pull_request:

jobs:
  build-and-test:

    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-nvcc

        configuration:
          - Debug

        include:
          - toolchain: linux-nvcc
            os: ubuntu-latest
            compiler: nvcc

    steps:
      - name: Setup CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.26
        id: cuda-toolkit
        use-github-cache: false
        with:
          cuda: '12.8.0'
          log-file-suffix: '${{matrix.toolchain}}.txt'
          use-github-cache: false
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache build
        uses: actions/cache@v4
        with:
          path: build/
          key: ${{ runner.os }}-build-${{ hashFiles('**/CMakeLists.txt') }}
          restore-keys: |
            ${{ runner.os }}-build- 

      - name: Configure (${{ matrix.configuration }})
        run: |
          cmake -S . -Bbuild -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -DENABLE_CUDA=ON
      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build --config ${{ matrix.configuration }}

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}

      - name: Upload build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build/
